### ISSUE TITLE
Training on a custom dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [wmcnally/evopose2d#1]
How do I train on a custom dataset? Is there any template?

**Comment by wmcnally** [comment]
Thank you for your interest in EvoPose2D. To train on your own dataset, you should modify `write_tfrecords.py` to read your own data and write the TFRecords. Then you can simply modify the yaml file to point to those TFRecords. You should also set the number of keypoints in the yaml file. Hope this helps.
