### ISSUE TITLE
Other data

### ISSUE THREAD

**Issue by ttdd11** [wmcnally/evopose2d#11]
Amazing work and very interesting paper.

In terms of using this on other data (such as hand data sets), is it as simple as changing the tf.records file to have those joints?

I see in the coco.py there are some joint defines, but nothing really in the yaml files.

Also, in the coco.py there are some upper body defines. Should these be modified as well? To address rotational bias in the data sets, can the rotational parameters be further modified to include more rotation.

Sorry about all the questions and thank you again for your amazing contribution.

**Comment by wmcnally** [comment]
Thank you for your interest in the paper. Yes, it's a matter of writing new tfrecords that are in the same format. There are a few things hardcoded right now (e.g., length of the `"joints"` feature in the `parse_record` function of `dataloader.py`), but I am in the process of cleaning up the code to help facilitate custom training. I will let you know when the updates are pushed.

**Comment by ttdd11** [comment]
Sounds good to me. I'm happy to test using other data sources and try other rotational paradigms if you like. Again, very cool work.

Let me know when the updates are pushed!
