### ISSUE TITLE
Rotation data augmentation

### ISSUE THREAD

**Issue by ttdd11** [wmcnally/evopose2d#12]
Sorry for flooding with issues. I can't find too much information regarding the data augmentation scheme. Specifically, I'm looking for joint symmetry and how this is handled in image mirroring, and adding more rotations (ie. 0-360 deg). Is this something that is parameterized in the repo? Thanks again for your help and amazing work.

**Comment by wmcnally** [comment]
The data augmentation configuration is defined in the default COCO config. See `dataset/coco.py`. The yaml files can override these values. Joint symmetry is handled using the `cfg.DATASET.KP_FLIP` attribute. Augmentation is applied in the `preprocess` function in `dataset/dataloader.py`.

**Comment by ttdd11** [comment]
I'll take look there, thanks!
