### ISSUE TITLE
tf_example from write_tfrecords.py uses wrong coco_path

### ISSUE THREAD

**Issue by tcwhalen** [wmcnally/evopose2d#14]
In write_tfrecords, the dict passed to tf_example contains the path relative to args.coco_path, but tf_example is trying to access it from the working directory. I fixed this by passing coco_path to tf_example and changing line 30 to:

image_raw = open(coco_path + "/annotations/" + sample_dict['img_path'], 'rb').read()

which I believe should always work if coco_path is correct and the data is organized correctly.

I imagine there may be a better solution than changing all the tf_exaple function calls to accept coco_path but this was a quick and easy fix for my purposes.

**Comment by wmcnally** [comment]
If you used an absolute path for the --coco-path argument, sample_dict['img_path'] should contain the full path to the image. See line 73 in write_tfrecords.py.
