### ISSUE TITLE
README should include instructions to obtain person_keypoints_val2017.json

### ISSUE THREAD

**Issue by tcwhalen** [wmcnally/evopose2d#15]
To run demo.py, the the coco data requires an annotations folder including person_keypoints_val2017.json. This can be obtained from the 2017 Train/Val annotations [241MB] zip file at https://cocodataset.org/#download, but is not included in the images or person detections json from steps 5 and 6 in the readme.

**Comment by wmcnally** [comment]
Thanks. I updated the instructions.
