### ISSUE TITLE
Config file (in coco.py) only suitable for XS model

### ISSUE THREAD

**Issue by tcwhalen** [wmcnally/evopose2d#17]
The cfg given in coco.py has

```
cn.DATASET.INPUT_SHAPE = [256, 192, 3]
```

This is the correct size for evopose2d_XS_f32.h5, but not for the three larger models (S, M, and L). Of course, one can edit coco.py to put the correct input sizes in, but I'm not sure if there are other differences in the configurations for the four models.

Could you provide the other training configs? Also, the demo currently says to download any of the four models, but it seems that XS is the one that should be recommended to avoid these size mismatches with the cfg.

**Comment by wmcnally** [comment]
These attributes are overwritten in the training config yaml files. Please see the config files here:
[https://github.com/wmcnally/evopose2d/tree/master/configs](https://github.com/wmcnally/evopose2d/tree/master/configs)

For the demo, use the command line argument --cfg to specify the config file that corresponds to the model you downloaded.
