### ISSUE TITLE
Convert TPU trained model to float32

### ISSUE THREAD

**Issue by ttdd11** [wmcnally/evopose2d#19]
Again, thank you for all the hard work. Once the model is trained on the TPU with float16, what is the process to convert these to float 32? Or does the entire model need to be trained as float32 in order to run as float 32?

**Comment by wmcnally** [comment]
If there is a way, I am not aware of it. However, I have provided the trained models in both float32 and bfloat16 format:
[https://drive.google.com/drive/u/2/folders/1neywqc7OC5dRErQJFCnCor5fphkKCzHh](https://drive.google.com/drive/u/2/folders/1neywqc7OC5dRErQJFCnCor5fphkKCzHh)

**Comment by ttdd11** [comment]
@wmcnally thanks for the reply. So I assume the float32 models were also trained on the TPU but with smaller batch size (and consequently a longer train time)?

**Comment by wmcnally** [comment]
Yes. I lowered the train batch sizes as follows:
EvoPose2D-L: 128 to 32
EvoPose2D-M: 256 to 192
EvoPose2D-S: 512 to 256
EvoPose2D-XS: no change

**Comment by ttdd11** [comment]
No problem I think we can experiment with that! Thanks a ton for your fast response.
