### ISSUE TITLE
how to run the demo?

### ISSUE THREAD

**Issue by pys0531** [wmcnally/evopose2d#2]
I want to run the demo in win or linux.
How do I operate an image or video?

**Comment by wmcnally** [comment]
I added a demo script. Please see instructions in updated README. If you would like to run on your own images, you will first need to use a person detector to get the bounding boxes.

**Comment by josemusso** [comment]
Hi @wmcnally ! Which person detectors have you tested? And how is the performance (fps) with it? I was thinking about YOLOv5 to give it a try. Thanks

**Comment by wmcnally** [comment]
Hi @josemusso -- I have not tested the full pipeline. I was using preprocessed bounding boxes for development purposes. YOLOv5 sounds like a great choice :) If you find a good TF2 YOLOv5 implementation, please let me know.

**Comment by josemusso** [comment]
I've connected your detector with a MobileNetV2 person detector and it runs at about 6-7 fps on a 1660ti max-q. Gonna fork and upload it soon if you want to test it. I can send you some demos too if you want to.
