### ISSUE TITLE
evopose_2d_XS_f32 does not run at 136 fps

### ISSUE THREAD

**Issue by naruto-raj** [wmcnally/evopose2d#21]
during inference the model runs at 32-36 fps and not more than that on 2080ti

**Comment by wmcnally** [comment]
FYI 136 fps does not include person detection. I just uploaded the code to test inference speed. The following command gives 136 fps on my machine with a TITAN Xp GPU: 

`$ python inference_speed.py -bs 1 -c evopose2d_XS_f32.yaml --gpu`
