### ISSUE TITLE
Effect of sigma

### ISSUE THREAD

**Issue by ttdd11** [wmcnally/evopose2d#24]
Again, amazing work. 

Do you believe that sigma (when generating heatmaps) will have any effect on output results? To me, the value creates heatmaps that are quite large and possibly overlap the mirrored joint (such as in the eyes).

Have you run any ablations on this value?

**Comment by wmcnally** [comment]
If I recall correctly, I did test slightly smaller sigma and slightly larger. The current value seems to work best, and is supported by other works as well. Overlap isn't an issue because each keypoint has its own heatmap.

**Comment by ttdd11** [comment]
Is there a downside to making this smaller from an optimization standpoint? For features with larger errors associated with the annotation, larger heatmaps are likely better, but for granular features such as the eyes, I would think that smaller would be better. 

What is your take on this? Still use the same size? For the eyes, the activations from the sample networks are about as big as the face (with 200 as the threshold).

**Comment by wmcnally** [comment]
I cannot say for sure. It sounds intuitive, but that doesn't always mean it works better. Maybe it disrupts learning because now the model needs to learn the different sizes as well as their positions? You could try using keypoint-specific sigmas and see what happens. You could base your sigmas off the [OKS metric for COCO](https://cocodataset.org/#keypoints-eval):

"the σ's are .026, .025, .035, .079, .072, .062, .107, .087, & .089 for the nose, eyes, ears, shoulders, elbows, wrists, hips, knees, & ankles"

**Comment by ttdd11** [comment]
I can test that and report back if you like.

Now my only concern would be that larger heatmaps would dominate the loss. Is this concern founded? Would the loss need to be scaled proportionally?

**Comment by wmcnally** [comment]
You might be right. But on the other hand, maybe the keypoints with smaller sigmas are easier to learn and thus don't need as much loss weight. Hard to say... In my [recent work](https://github.com/wmcnally/kapao), I found that the keypoints with smaller sigmas are detected with higher confidence, which might indicate that they are easier to learn.

**Comment by ttdd11** [comment]
Sounds great, thanks for the input.

**Comment by ttdd11** [comment]
Did a bit more digging on this:

What I found is that data sets with more granular features (such as coco with hands) seem to have great detections for the larger keypoints, and less accurate detection for the smaller keypoints. I wonder if either of these are possible:
1. The more granular and complicated keypoints just need more loss  (an even distribution among all the joints is an issue)
2.  The architecture itself was setup and optimized for sets with just larger keypoints. For different data sets, do you believe the architecture would need to be modified (ie. "Evolved") again to better suit keypoints that require higher granularity?

Thank you again for your great contribution and sorry for all of these questions.
