### ISSUE TITLE
inference time (s/im)?

### ISSUE THREAD

**Issue by klwong126** [wmcnally/evopose2d#3]
May I know the inference time of the model?

**Comment by wmcnally** [comment]
I have not tested the inference time. It will vary based on input resolution, batch size, and hardware.

**Comment by cjangrist** [comment]
do you have reference inference times for training/validation sets?

256x256, single GPU, etc.

**Comment by wmcnally** [comment]
I measured the inference times on my machine, see below. Frames per second averaged over 1k forward passes on NVIDIA TITAN Xp GPU using a batch size of 1. 

```
EvoPose2D-XS   136 FPS
EvoPose2D-S    102 FPS
EvoPose2D-M     36 FPS
EvoPose2D-L     16 FPS
```
