### ISSUE TITLE
 (0) Invalid argument:  Key: joints.  Can't parse serialized Example.

### ISSUE THREAD

**Issue by MiladGhorbaniG** [wmcnally/evopose2d#6]
I created a custom keypoint dataset with MS COCO format and then created tfrecords and then change yaml files, but when training I faced the following error:

> Running on single GPU  /device:GPU:0
> Number of accelerators:  1
> Training hrnet_w32_256x192 (28.59M / 7.65G) on GPU/CPU for 200 epochs
> Traceback (most recent call last):
>   File "train.py", line 188, in <module>
>     model, meta_data = train(strategy, cfg)
>   File "train.py", line 121, in train
>     train_step(train_iterator)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
>     result = self._call(*args, **kwds)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 840, in _call
>     return self._stateless_fn(*args, **kwds)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
>     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
>     cancellation_manager=cancellation_manager)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager))
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 550, in call
>     ctx=ctx)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
>     inputs, attrs, num_outputs)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
>   (0) Invalid argument:  Key: joints.  Can't parse serialized Example.
> 	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
> 	 [[IteratorGetNext]]
> 	 [[StatefulPartitionedCall/hrnet/s3/m0/b11/relu1/Relu/_902]]
>   (1) Invalid argument:  Key: joints.  Can't parse serialized Example.
> 	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
> 	 [[IteratorGetNext]]
>   (2) Invalid argument:  Key: joints.  Can't parse serialized Example.
> 	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
> 	 [[IteratorGetNext]]
> 	 [[ConstantFolding/PartitionedCall/gradients/hrnet/s1/m0/b01/conv3/Conv2D_grad/ShapeN-matshapes-1/_10708]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_step_133797]
> 
> Function call stack:
> train_step -> train_step -> train_step

**Comment by MiladGhorbaniG** [comment]
for this issue I changed the input shape to (1920,1088) but it turned to the following error 

> Running on single GPU


>   /device:GPU:0
> Number of accelerators:  1
> Traceback (most recent call last):
>   File "train.py", line 188, in <module>
>     model, meta_data = train(strategy, cfg)
>   File "train.py", line 74, in train
>     model = EvoPose(cfg)
>   File "/content/drive/My Drive/evopose2d/nets/evopose2d.py", line 188, in EvoPose
>     **args)
>   File "/content/drive/My Drive/evopose2d/nets/evopose2d.py", line 250, in block
>     name=name + 'expand_conv')(inputs)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
>     input_list)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1095, in _functional_construction_call
>     with graph.as_default(), backend.name_scope(self._name_scope()):
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6631, in __enter__
>     scope_name = scope.__enter__()
>   File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
>     return next(self.gen)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 4190, in name_scope
>     raise ValueError("'%s' is not a valid scope name" % name)
> ValueError: 'block2{_expand_conv/' is not a valid scope name

**Comment by wmcnally** [comment]
It appears scaling the network to that input size causes issues with layer naming. In your config file, try setting MODEL.DEPTH_COEFFICIENT and MODEL.WIDTH_COEFFICIENT to something like 0.5 or 0.25.
