### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'

### ISSUE THREAD

**Issue by bkw0622** [wmcnally/evopose2d#7]
I have error `AttributeError:` 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'.

`$ python3 validate.py -c evopose2d_M_f32.yaml'

'Running on CPU
Number of accelerators:  1
Traceback (most recent call last):
  File "validate.py", line 142, in <module>
    AP = validate(strategy, cfg, split='val')
  File "validate.py", line 73, in validate
    scores = np.concatenate(scores.values, axis=0)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'values'
`

How can i solve this problem?

**Comment by wmcnally** [comment]
Hi @bkw0622, I added a fix. Please try running validate.py again.
